openapi: 3.0.0
info:
  title: Game Orchestrator Service
  description: >
    Service central pilotant le gameplay. Il orchestre les appels entre le LevelDesign, 
    le HeroService, le CombatService et le SauvegardeService.
  version: 1.5.0

servers:
  - url: http://localhost:3003

paths:
  /game/next-step:
    post:
      summary: "Avancer dans le donjon"
      description: "Récupère l'état de la partie, gère le combat éventuel et passe à la salle suivante."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [userId]
              properties:
                userId: { type: string }
      responses:
        '200':
          description: "Résultat du tour (exploration, combat ou fin)"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameState'

components:
  schemas:
    HeroClass:
      type: string
      enum: [WARRIOR, TANK, ASSASSIN]
    
    GameInitResponse:
      type: object
      properties:
        status: { type: string, example: "STARTING" }
        userId: { type: string }
        dungeonId: { type: string }
        currentRoom: { $ref: '#/components/schemas/Room' }
        message: { type: string }

    GameState:
      type: object
      properties:
        status:
          type: string
          enum: [EXPLORING, GAME_OVER, DUNGEON_CLEARED]
        heroHp: { type: integer }
        goldLooted: { type: integer }
        currentRoom: { $ref: '#/components/schemas/Room' }
        log:
          type: array
          items: { type: string }
        message: { type: string }

    Room:
      type: object
      properties:
        id: { type: string, format: uuid }
        index: { type: integer }
        dialogue: { type: string }
        monster: { $ref: '#/components/schemas/Monster' }

    Monster:
      type: object
      properties:
        name: { type: string }
        stats:
          type: object
          properties:
            hp: { type: integer }
            atk: { type: integer }
            gold: { type: integer }
            vit: { type: integer }

    Item:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
        effect: { type: string }
        value: { type: integer }